### ISSUE TITLE
Can only make a board from root directory

### ISSUE THREAD

**Issue by JaKXz** [amckinnell/nutrella#8]
It would be nice to be able to create a nutrella board from any subdirectory of a given project.

I've tracked it down to: https://github.com/amckinnell/nutrella/blob/master/lib/nutrella/task_board_name.rb#L8

so I'll hopefully have a PR [soon | by the end of the weekend] :)

**Comment by amckinnell** [comment]
Done. Try it now with the 0.6.0 release.
